data:
    image_size: 64
    channels: 3
    training_keep_image_size: False
    testing_keep_image_size: True
    num_workers: 4
    train_data_dir: '/Your_dataroot/train/'  # path to directory of train data
    test_data_dir: '/Your_dataroot/test/'  # path to directory of test data
    test_save_dir: 'Your_project_path/OBS_Diffusion/result'
    val_save_dir: 'Your_project_path/OBS_Diffusion/validation/'
    grid_r: 12
    conditional: True
    tensorboard: 'Your_project_path/OBS_Diffusion/logs'

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    use_vlb: False
    learn_sigma: False

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 8
    batch_size: 12
    n_epochs: 500
    n_iters: 2000000
    snapshot_freq: 30  # model save frequency
    validation_freq: 10000  # validation frequency
    resume: '/Your_save_root/diffusion_model'  # path to save the model
    seed: 61 # random seed
    amp: False # automatic mixed precision
    init_scale: 2.0 ** 16

sampling:
    batch_size: 1
    last_only: True
    sampling_timesteps: 50

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    warmup_epochs: 20
    lr_schedule: "constant"
    amsgrad: False
    eps: 0.00000001
